version: '3.8'

services:
  fooddiaries_db:
    container_name: fooddiaries_db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fooddiaries
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - fooddiaries

  fooddiaries_phpmyadmin:
    container_name: fooddiaries_phpmyadmin
    image: phpmyadmin
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - fooddiaries
    depends_on:
      - fooddiaries_db
  
networks:
  fooddiaries:
    driver: bridge