version: '3.8'

services:
  db:
    container_name: fooddiaries_db
    build:
      context: ./server
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=foodDiaries
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      # - ./mysql:/var/lib/mysql
      - foodDiaries_volume:/var/lib/mysql
    networks:
      - fooddiaries

  fooddiaries_phpmyadmin:
    container_name: fooddiaries_phpmyadmin
    image: phpmyadmin
    ports:
      - 80:80
    restart: unless-stopped
    networks:
      - fooddiaries
    depends_on:
      - db
  
networks:
  fooddiaries:
    driver: bridge

volumes:
  foodDiaries_volume: